### ISSUE TITLE
size of response buffer not updated when executing commands

### ISSUE THREAD

**Issue by faustochiatante** [Microsoft/MSRSec#27]
Hi everybody,

Thank you for the wonderful job done in this repo, it is being very helpful for the project of my master thesis. Using your TA I've been having two doubts at the moment:

* I'm writing a Linux client (as i didn't find one available) in order to allow the ftpm running in OPTEE to communicate with TSS. I noticed that when submitting a regular TPM command, in `fTPM_Submit_Command` the size attribute of the response buffer (`params[1].memref.size`) is not updated with the value of `respLen`, contrarily to what is done for PPI commands (line 386 of ftpm.c). Is there a specific reason for this behavior?

* Also, I can't seem to find an implemented way to invoke platform signals through the OPTEE interface. Should I add entries in `TA_InvokeCommandEntryPoint` to handle them, like it has been done for regular commands and physical presence, or there is already a way to do so?

Thanks in advance.

**Comment by faustochiatante** [comment]
I went on and implemented Platform Control support across the OPTEE interface. I've done this by adding a new command which covers all the hardware signals managed by TSS2. To be clearer, the ones received on the control socket when using a TPM2 simulator.
 I'm still not sure that this is a good idea, though. Should these signals be kept shielded inside OPTEE? Was platform control omitted from the project on purpose, to prevent applications in the unsecure world from tampering with these signals?

Thanks!!

**Comment by DMattoon** [comment]
The inability to access platform functions is intentional.  In this environment OP-TEE itself constitutes "the platform" and even then, OP-TEE does not exert direct control over platform functions.  Instead, the TA takes it's cues from TEE Client API calls, see platform calls in fTPM.c.

I would recommend against opening up access to platform functions because it is dangerous and unnecessary.  That said, if in your implementation there is some particular value in permitting access to these functions, that's fine, but I would take great care in doing so.

On your first question on response length.  There is no particular reason the memref.size field is not updated (would be good to add it I suppose).  The memref.size is validated to ensure the entire response will fit, and that's all we really care about.  This is because the size of the response buffer is included within the response.

Assuming the memref buffer is sufficiently large, the recipient takes the response size directly from the the response itself as this is authoritative.  The memref.size is redundant (but there's no harm in updating it and you could argue that not updating it is a bug).

**Comment by faustochiatante** [comment]
Thank you very much. I imagined it was intentional, but I couldn't find it written in the code or README so I was still unsure. It was a good exercise anyway to add it. Your response clarified all of it perfectly. Maybe it would be useful to add a comment about it for people that come from the Microsoft Simulator (with complete access to all the functions) and don't understand the introduced limitations and the logic behind them.

Regarding my question about the response length: I agree that it is unnecessary, it only seemed strange that it was updated for PPI commands and not for regular commands. So I asked to make sure that it wasn't intentional. I'm fairly new to open source projects and it's always complicated to distinguish between what is put there on purpose and what is a bug. 

I'll consider opening a pull request to add the update of response length and I'll close the issue!
Thank you again!
